export default interface IUser {
  username: string,
  email: string,
  password: string,
  telefono: string,
  nome: string,
  cognome: string,
  via: string,
  nCivico: string,
  cap: string,
  citta: string,
  nazione: string,
  dataIscrizione: string,
  isLogged: boolean,
  _id?: string,
}
